"""empty message

Revision ID: 51ead671f455
Revises: 374605fc26a3
Create Date: 2026-04-05 00:52:42.893434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ead671f455'
down_revision = '374605fc26a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_mr', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_mr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tagline_sk', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('collection', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('season', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('low_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('save_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tax_info', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('badge', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('badge')
        batch_op.drop_column('tax_info')
        batch_op.drop_column('save_text')
        batch_op.drop_column('low_stock')
        batch_op.drop_column('sku')
        batch_op.drop_column('season')
        batch_op.drop_column('collection')
        batch_op.drop_column('tagline_sk')
        batch_op.drop_column('description_mr')
        batch_op.drop_column('name_mr')

    # ### end Alembic commands ###
