"""add rating_display review_count

Revision ID: 61b4819273f1
Revises: a96debedca5d
Create Date: 2026-04-05 16:22:10.860594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b4819273f1'
down_revision = 'a96debedca5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_display', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating_display')

    # ### end Alembic commands ###
