"""add product rich content fields

Revision ID: a96debedca5d
Revises: bedd6236f9d2
Create Date: 2026-04-05 16:13:09.133323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96debedca5d'
down_revision = 'bedd6236f9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('colors_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('highlights_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specs_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('offers_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wash_care_mr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('fit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('default_size', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('default_size')
        batch_op.drop_column('fit')
        batch_op.drop_column('tags')
        batch_op.drop_column('slug')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('delivery_json')
        batch_op.drop_column('wash_care_mr')
        batch_op.drop_column('offers_json')
        batch_op.drop_column('specs_json')
        batch_op.drop_column('highlights_json')
        batch_op.drop_column('colors_json')
        batch_op.drop_column('sizes_json')

    # ### end Alembic commands ###
