"""add image_2 image_3 image_4 to products

Revision ID: bedd6236f9d2
Revises: 51ead671f455
Create Date: 2026-04-05 15:51:22.792872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedd6236f9d2'
down_revision = '51ead671f455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_2', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_3', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_4', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_4')
        batch_op.drop_column('image_3')
        batch_op.drop_column('image_2')

    # ### end Alembic commands ###
